# Generated by Django 5.1.6 on 2025-03-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ['created_at', 'owner', 'payment_amount', 'paid_course', 'paid_lesson', 'payment_method'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionforcourse',
            options={'ordering': ['created_at', 'owner', 'course'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='subscriptionforcourse',
            old_name='user',
            new_name='owner',
        ),
    ]
